-- MySQL Script generated by MySQL Workbench
-- Mon Jan  7 13:27:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema acoes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `acoes`;

-- -----------------------------------------------------
-- Schema acoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acoes` DEFAULT CHARACTER SET utf8;
USE `acoes`;

-- -----------------------------------------------------
-- Table `acoes`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`alumno`;

CREATE TABLE IF NOT EXISTS `acoes`.`alumno`
(
  `codigo`              INT                            NOT NULL AUTO_INCREMENT,
  `nombre`              VARCHAR(45)                    NOT NULL,
  `apellidos`           VARCHAR(45)                    NOT NULL,
  `estado`              VARCHAR(15)                    NULL,
  `sexo`                ENUM ('Masculino', 'Femenino') NOT NULL,
  `foto`                VARCHAR(100)                   NULL,
  `fecha_nacimiento`    DATE                           NOT NULL,
  `fecha_entrada_acoes` DATE                           NOT NULL,
  `fecha_alta`          DATE                           NOT NULL,
  `fecha_salida_acoes`  DATE                           NULL,
  `grado_curso`         INT                            NOT NULL,
  `colonia_procedencia` VARCHAR(45)                    NOT NULL,
  `colonia_actual`      VARCHAR(45)                    NOT NULL,
  `observaciones`       VARCHAR(100)                   NULL,
  PRIMARY KEY (`codigo`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`socio`;

CREATE TABLE IF NOT EXISTS `acoes`.`socio`
(
  `numero_de_socio` INT          NOT NULL AUTO_INCREMENT,
  `nombre`          VARCHAR(45)  NOT NULL,
  `apellidos`       VARCHAR(45)  NOT NULL,
  `estado`          VARCHAR(15)  NULL,
  `nif`             VARCHAR(9)   NOT NULL,
  `direccion`       VARCHAR(45)  NOT NULL,
  `poblacion`       VARCHAR(30)  NOT NULL,
  `codigo_postal`   VARCHAR(10)  NOT NULL,
  `provincia`       VARCHAR(25)  NOT NULL,
  `telefono_fijo`   INT          NULL,
  `telefono_movil`  INT          NOT NULL,
  `email`           VARCHAR(45)  NOT NULL,
  `relacion`        VARCHAR(45)  NULL,
  `certificado`     BIT(1)       NOT NULL,
  `sector`          VARCHAR(50)  NOT NULL,
  `fecha_alta`      DATE         NOT NULL,
  `fecha_baja`      DATE         NULL,
  `observaciones`   VARCHAR(100) NULL,
  PRIMARY KEY (`numero_de_socio`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`proyecto`;

CREATE TABLE IF NOT EXISTS `acoes`.`proyecto`
(
  `id`                     INT          NOT NULL AUTO_INCREMENT,
  `nombre`                 VARCHAR(45)  NOT NULL,
  `descripcion`            VARCHAR(100) NOT NULL,
  `reparto_combustible`    DOUBLE       NOT NULL,
  `reparto_mantenimiento`  DOUBLE       NOT NULL,
  `reparto_cta_contenedor` DOUBLE       NOT NULL,
  `region_ayuda`           VARCHAR(45)  NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`sede`;

CREATE TABLE IF NOT EXISTS `acoes`.`sede`
(
  `region` ENUM ('Espana') NOT NULL,
  `id`     INT             NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`centro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`centro`;

CREATE TABLE IF NOT EXISTS `acoes`.`centro`
(
  `id`       INT         NOT NULL AUTO_INCREMENT,
  `nombre`   VARCHAR(50) NOT NULL,
  `proyecto` INT         NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_centro_proyecto_idx` (`proyecto` ASC),
  CONSTRAINT `fk_centro_proyecto`
    FOREIGN KEY (`proyecto`)
      REFERENCES `acoes`.`proyecto` (`id`)
      ON DELETE CASCADE
      ON UPDATE CASCADE
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`usuario`;

CREATE TABLE IF NOT EXISTS `acoes`.`usuario`
(
  `id`                 INT                                                 NOT NULL AUTO_INCREMENT,
  `nombre`             VARCHAR(50)                                         NOT NULL,
  `email`              VARCHAR(50)                                         NOT NULL,
  `contrasena`         VARCHAR(15)                                         NOT NULL,
  `rol`                ENUM ('Agente', 'GerenteSede', 'GerenteRegional', 'CoordinadorLocal', 'CoordinadorGeneral',
                             'AdministradorLocal', 'AdministradorGeneral') NOT NULL,
  `sede_usuario_local` INT                                                 NULL,
  `centro_`            INT                                                 NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_sede1_idx` (`sede_usuario_local` ASC),
  INDEX `fk_usuario_centro1_idx` (`centro_` ASC),
  CONSTRAINT `fk_usuario_sede1`
    FOREIGN KEY (`sede_usuario_local`)
      REFERENCES `acoes`.`sede` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_centro1`
    FOREIGN KEY (`centro_`)
      REFERENCES `acoes`.`centro` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`registro_economico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`registro_economico`;

CREATE TABLE IF NOT EXISTS `acoes`.`registro_economico`
(
  `id`                  INT                        NOT NULL AUTO_INCREMENT,
  `fecha`               DATE                       NOT NULL,
  `tipo`                ENUM ('Ingreso', 'Egreso') NOT NULL,
  `concepto`            VARCHAR(45)                NOT NULL,
  `importe`             DOUBLE                     NOT NULL,
  `codigo_beneficiario` INT                        NULL,
  `observaciones`       VARCHAR(100)               NULL,
  `codigo_servicio`     INT                        NULL,
  `proyecto`            INT                        NOT NULL,
  `numero_socio`        INT                        NULL,
  `responsable`         INT                        NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registro_alumno_idx` (`codigo_beneficiario` ASC),
  INDEX `fk_registro_proyecto_idx` (`proyecto` ASC),
  INDEX `fk_RegistroEconomico_Socio1_idx` (`numero_socio` ASC),
  INDEX `fk_registro_economico_usuario1_idx` (`responsable` ASC),
  CONSTRAINT `fk_registro_alumno`
    FOREIGN KEY (`codigo_beneficiario`)
      REFERENCES `acoes`.`alumno` (`codigo`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_proyecto`
    FOREIGN KEY (`proyecto`)
      REFERENCES `acoes`.`proyecto` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroEconomico_Socio1`
    FOREIGN KEY (`numero_socio`)
      REFERENCES `acoes`.`socio` (`numero_de_socio`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_economico_usuario1`
    FOREIGN KEY (`responsable`)
      REFERENCES `acoes`.`usuario` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`esta_en`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`esta_en`;

CREATE TABLE IF NOT EXISTS `acoes`.`esta_en`
(
  `alumno`      INT  NOT NULL,
  `centro`      INT  NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin`    DATE NULL,
  PRIMARY KEY (`alumno`, `centro`),
  INDEX `fk_estaen_centro_idx` (`centro` ASC),
  CONSTRAINT `fk_estaen_alumno`
    FOREIGN KEY (`alumno`)
      REFERENCES `acoes`.`alumno` (`codigo`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_estaen_centro`
    FOREIGN KEY (`centro`)
      REFERENCES `acoes`.`centro` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`apadrinamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`apadrinamiento`;

CREATE TABLE IF NOT EXISTS `acoes`.`apadrinamiento`
(
  `id`           INT  NOT NULL AUTO_INCREMENT,
  `apadrinado`   INT  NOT NULL,
  `padrino`      INT  NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin`    DATE NULL,
  PRIMARY KEY (`id`, `apadrinado`, `padrino`),
  INDEX `fk_apadrinamiento_socio_idx` (`padrino` ASC),
  INDEX `fk_apadrinamiento_alumno1_idx` (`apadrinado` ASC),
  CONSTRAINT `fk_apadrinamiento_socio`
    FOREIGN KEY (`padrino`)
      REFERENCES `acoes`.`socio` (`numero_de_socio`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_apadrinamiento_alumno1`
    FOREIGN KEY (`apadrinado`)
      REFERENCES `acoes`.`alumno` (`codigo`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`administracion_apadrinamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`administracion_apadrinamiento`;

CREATE TABLE IF NOT EXISTS `acoes`.`administracion_apadrinamiento`
(
  `fecha_inicio`              DATE NOT NULL,
  `fecha_fin`                 DATE NULL,
  `agente`                    INT  NOT NULL,
  `apadrinamiento_id`         INT  NOT NULL,
  `apadrinamiento_apadrinado` INT  NOT NULL,
  `apadrinamiento_padrino`    INT  NOT NULL,
  PRIMARY KEY (`agente`, `fecha_inicio`),
  INDEX `fk_administracion_apadrinamiento_usuario1_idx` (`agente` ASC),
  INDEX `fk_administracion_apadrinamiento_apadrinamiento1_idx` (`apadrinamiento_id` ASC, `apadrinamiento_apadrinado`
                                                                ASC, `apadrinamiento_padrino` ASC),
  CONSTRAINT `fk_administracion_apadrinamiento_usuario1`
    FOREIGN KEY (`agente`)
      REFERENCES `acoes`.`usuario` (`id`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  CONSTRAINT `fk_administracion_apadrinamiento_apadrinamiento1`
    FOREIGN KEY (`apadrinamiento_id`, `apadrinamiento_apadrinado`, `apadrinamiento_padrino`)
      REFERENCES `acoes`.`apadrinamiento` (`id`, `apadrinado`, `padrino`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acoes`.`envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acoes`.`envio`;

CREATE TABLE IF NOT EXISTS `acoes`.`envio`
(
  `id`                        INT                                       NOT NULL AUTO_INCREMENT,
  `estado`                    ENUM ('Preparado', 'Enviado', 'Recibido') NOT NULL,
  `apadrinamiento_id`         INT                                       NOT NULL,
  `apadrinamiento_apadrinado` INT                                       NOT NULL,
  `apadrinamiento_padrino`    INT                                       NOT NULL,
  PRIMARY KEY (`id`, `apadrinamiento_id`, `apadrinamiento_apadrinado`, `apadrinamiento_padrino`),
  INDEX `fk_envio_apadrinamiento1_idx` (`apadrinamiento_id` ASC, `apadrinamiento_apadrinado` ASC,
                                        `apadrinamiento_padrino` ASC),
  CONSTRAINT `fk_envio_apadrinamiento1`
    FOREIGN KEY (`apadrinamiento_id`, `apadrinamiento_apadrinado`, `apadrinamiento_padrino`)
      REFERENCES `acoes`.`apadrinamiento` (`id`, `apadrinado`, `padrino`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
