-- MySQL Script generated by MySQL Workbench
-- jue 29 nov 2018 18:59:50 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(15) NULL,
  `sexo` ENUM('Masculino', 'Femenino') NOT NULL,
  `foto` VARCHAR(100) NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  `fechaDeEntradaACOES` DATE NOT NULL,
  `fechaDeAlta` DATE NOT NULL,
  `fechaSalidaACOES` DATE NULL,
  `gradoDelCurso` INT NOT NULL,
  `coloniaDeProcedencia` VARCHAR(45) NOT NULL,
  `coloniaActual` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Socio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Socio` (
  `numeroDeSocio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(15) NULL,
  `nif` VARCHAR(9) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `poblacion` VARCHAR(30) NOT NULL,
  `codigoPostal` VARCHAR(10) NOT NULL,
  `provincia` VARCHAR(25) NOT NULL,
  `telefonoFijo` INT NULL,
  `telefonoMovil` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `relacion` VARCHAR(45) NULL,
  `certificado` BIT(1) NOT NULL,
  `sector` VARCHAR(50) NOT NULL,
  `fechaAlta` DATE NOT NULL,
  `fechaBaja` DATE NULL,
  `observaciones` VARCHAR(100) NULL,
  PRIMARY KEY (`numeroDeSocio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(15) NOT NULL,
  `rol` ENUM('Agente', 'GerenteSede', 'GerenteRegional', 'CoordinadorLocal', 'CoordinadorGeneral', 'AdministradorLocal', 'AdministradorGeneral') NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proyecto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `repartoCombustible` DOUBLE NOT NULL,
  `repartoDeMantenimiento` DOUBLE NOT NULL,
  `repartoCtaContenedor` DOUBLE NOT NULL,
  `regionDeAyuda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Centro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Centro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Centro` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `proyecto` INT NOT NULL,
  PRIMARY KEY (`ID`, `proyecto`),
  INDEX `fk_centro_proyecto_idx` (`proyecto` ASC) VISIBLE,
  CONSTRAINT `fk_centro_proyecto`
    FOREIGN KEY (`proyecto`)
    REFERENCES `mydb`.`Proyecto` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsuarioLocal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UsuarioLocal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UsuarioLocal` (
  `ID` INT NOT NULL,
  `Centro_id` INT NOT NULL,
  PRIMARY KEY (`ID`, `Centro_id`),
  INDEX `fk_UsuarioLocal_Centro1_idx` (`Centro_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuariolocal_usuario`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioLocal_Centro1`
    FOREIGN KEY (`Centro_id`)
    REFERENCES `mydb`.`Centro` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_administrador_usuariolocal`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`UsuarioLocal` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ResponsableEconomico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ResponsableEconomico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ResponsableEconomico` (
  `ID` INT NOT NULL,
  `Administrador_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Administrador_ID`),
  INDEX `fk_ResponsableEconomico_Administrador1_idx` (`Administrador_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ResponsableEconomico_Administrador1`
    FOREIGN KEY (`Administrador_ID`)
    REFERENCES `mydb`.`Administrador` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegistroEconomico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RegistroEconomico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RegistroEconomico` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tipo` ENUM('Ingreso', 'Egreso') NOT NULL,
  `concepto` VARCHAR(45) NOT NULL,
  `importe` DOUBLE NOT NULL,
  `codigoBenficiario` INT NOT NULL,
  `observaciones` VARCHAR(100) NULL,
  `codigoServicio` INT NOT NULL,
  `responsable` INT NOT NULL,
  `proyecto` INT NOT NULL,
  `Socio_numeroDeSocio` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_registro_alumno_idx` (`codigoBenficiario` ASC) VISIBLE,
  INDEX `fk_registro_proyecto_idx` (`proyecto` ASC) VISIBLE,
  INDEX `fk_registro_responsable_idx` (`responsable` ASC) VISIBLE,
  INDEX `fk_RegistroEconomico_Socio1_idx` (`Socio_numeroDeSocio` ASC) VISIBLE,
  CONSTRAINT `fk_registro_responsable`
    FOREIGN KEY (`responsable`)
    REFERENCES `mydb`.`ResponsableEconomico` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_registro_alumno`
    FOREIGN KEY (`codigoBenficiario`)
    REFERENCES `mydb`.`Alumno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_proyecto`
    FOREIGN KEY (`proyecto`)
    REFERENCES `mydb`.`Proyecto` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroEconomico_Socio1`
    FOREIGN KEY (`Socio_numeroDeSocio`)
    REFERENCES `mydb`.`Socio` (`numeroDeSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstaEn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EstaEn` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EstaEn` (
  `alumno` INT NOT NULL,
  `centro` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  PRIMARY KEY (`alumno`, `centro`),
  INDEX `fk_estaen_centro_idx` (`centro` ASC) VISIBLE,
  CONSTRAINT `fk_estaen_alumno`
    FOREIGN KEY (`alumno`)
    REFERENCES `mydb`.`Alumno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estaen_centro`
    FOREIGN KEY (`centro`)
    REFERENCES `mydb`.`Centro` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sede` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `region` ENUM('España', 'Honduras') NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apadrinable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Apadrinable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Apadrinable` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_apadrinable_alumno`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Alumno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apadrinamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Apadrinamiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Apadrinamiento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `apadrinado` INT NOT NULL,
  `padrino` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  PRIMARY KEY (`ID`, `padrino`, `apadrinado`),
  INDEX `fk_apadrinamiento_apadrinable_idx` (`apadrinado` ASC) VISIBLE,
  INDEX `fk_apadrinamiento_socio_idx` (`padrino` ASC) VISIBLE,
  CONSTRAINT `fk_apadrinamiento_apadrinable`
    FOREIGN KEY (`apadrinado`)
    REFERENCES `mydb`.`Apadrinable` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apadrinamiento_socio`
    FOREIGN KEY (`padrino`)
    REFERENCES `mydb`.`Socio` (`numeroDeSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coordinador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Coordinador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Coordinador` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_coordinador_usuariolocal`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`UsuarioLocal` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsuarioSede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UsuarioSede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UsuarioSede` (
  `sede` INT NOT NULL,
  `ID` INT NOT NULL,
  INDEX `fk_usuariosede_sede_idx` (`sede` ASC) VISIBLE,
  PRIMARY KEY (`ID`, `sede`),
  CONSTRAINT `fk_usuariosede_sede`
    FOREIGN KEY (`sede`)
    REFERENCES `mydb`.`Sede` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UsuarioSede_Usuario1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Agente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Agente` (
  `ID` INT NOT NULL,
  INDEX `fk_usuariosede_agente_idx` (`ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_usuariosede_agente`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`UsuarioSede` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AdministracionApadrinamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AdministracionApadrinamiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AdministracionApadrinamiento` (
  `apadrinamiento` INT NOT NULL,
  `agente` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  INDEX `fk_adminap_agente_idx` (`agente` ASC) VISIBLE,
  PRIMARY KEY (`apadrinamiento`, `agente`),
  CONSTRAINT `fk_adminap_apadrinamiento`
    FOREIGN KEY (`apadrinamiento`)
    REFERENCES `mydb`.`Apadrinamiento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adminap_agente`
    FOREIGN KEY (`agente`)
    REFERENCES `mydb`.`Agente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gerente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gerente` (
  `ID` INT NOT NULL,
  INDEX `fk_usuariosede_gerente_idx` (`ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_gerente_responsable`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`ResponsableEconomico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuariosede_gerente`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`UsuarioSede` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Envio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Envio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `apadrinamiento` INT NOT NULL,
  `estado` ENUM('Preparado', 'Enviado', 'Recibido') NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `apadrinamiento_UNIQUE` (`apadrinamiento` ASC) VISIBLE,
  CONSTRAINT `fk_envio_apadrinamiento`
    FOREIGN KEY (`apadrinamiento`)
    REFERENCES `mydb`.`Apadrinamiento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Becado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Becado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Becado` (
  `ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_becado_alumno`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Alumno` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
