-- MySQL Script generated by MySQL Workbench
-- lun 03 dic 2018 18:02:25 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alumno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alumno` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(15) NULL,
  `sexo` ENUM('Masculino', 'Femenino') NOT NULL,
  `foto` VARCHAR(100) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_entrada_acoes` DATE NOT NULL,
  `fecha_alta` DATE NOT NULL,
  `fecha_salida_acoes` DATE NULL,
  `grado_curso` INT NOT NULL,
  `colonia_procedencia` VARCHAR(45) NOT NULL,
  `colonia_actual` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`socio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`socio` (
  `numero_de_socio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(15) NULL,
  `nif` VARCHAR(9) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `poblacion` VARCHAR(30) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `provincia` VARCHAR(25) NOT NULL,
  `telefono_fijo` INT NULL,
  `telefono_movil` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `relacion` VARCHAR(45) NULL,
  `certificado` BIT(1) NOT NULL,
  `sector` VARCHAR(50) NOT NULL,
  `fecha_alta` DATE NOT NULL,
  `fecha_baja` DATE NULL,
  `observaciones` VARCHAR(100) NULL,
  PRIMARY KEY (`numero_de_socio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(15) NOT NULL,
  `rol` ENUM('Agente', 'GerenteSede', 'GerenteRegional', 'CoordinadorLocal', 'CoordinadorGeneral', 'AdministradorLocal', 'AdministradorGeneral') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `reparto_combustible` DOUBLE NOT NULL,
  `reparto_mantenimiento` DOUBLE NOT NULL,
  `reparto_cta_contenedor` DOUBLE NOT NULL,
  `region_ayuda` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`centro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`centro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`centro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `proyecto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_centro_proyecto_idx` (`proyecto` ASC),
  CONSTRAINT `fk_centro_proyecto`
    FOREIGN KEY (`proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_local` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_local` (
  `id` INT NOT NULL,
  `centro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_UsuarioLocal_Centro1_idx` (`centro` ASC),
  CONSTRAINT `fk_usuariolocal_usuario`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioLocal_Centro1`
    FOREIGN KEY (`centro`)
    REFERENCES `mydb`.`centro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administrador_usuariolocal`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`usuario_local` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsable_economico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`responsable_economico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`responsable_economico` (
  `id` INT NULL,
  `administrador` INT NULL,
  PRIMARY KEY (`id`, `administrador`),
  INDEX `fk_ResponsableEconomico_Administrador1_idx` (`administrador` ASC),
  CONSTRAINT `fk_ResponsableEconomico_Administrador1`
    FOREIGN KEY (`administrador`)
    REFERENCES `mydb`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_economico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_economico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_economico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tipo` ENUM('Ingreso', 'Egreso') NOT NULL,
  `concepto` VARCHAR(45) NOT NULL,
  `importe` DOUBLE NOT NULL,
  `codigo_beneficiario` INT NOT NULL,
  `observaciones` VARCHAR(100) NULL,
  `codigo_servicio` INT NOT NULL,
  `responsable` INT NOT NULL,
  `proyecto` INT NOT NULL,
  `numero_socio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registro_alumno_idx` (`codigo_beneficiario` ASC),
  INDEX `fk_registro_proyecto_idx` (`proyecto` ASC),
  INDEX `fk_registro_responsable_idx` (`responsable` ASC),
  INDEX `fk_RegistroEconomico_Socio1_idx` (`numero_socio` ASC),
  CONSTRAINT `fk_registro_responsable`
    FOREIGN KEY (`responsable`)
    REFERENCES `mydb`.`responsable_economico` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_registro_alumno`
    FOREIGN KEY (`codigo_beneficiario`)
    REFERENCES `mydb`.`alumno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_proyecto`
    FOREIGN KEY (`proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroEconomico_Socio1`
    FOREIGN KEY (`numero_socio`)
    REFERENCES `mydb`.`socio` (`numero_de_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`esta_en`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`esta_en` ;

CREATE TABLE IF NOT EXISTS `mydb`.`esta_en` (
  `alumno` INT NOT NULL,
  `centro` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  PRIMARY KEY (`alumno`, `centro`),
  INDEX `fk_estaen_centro_idx` (`centro` ASC),
  CONSTRAINT `fk_estaen_alumno`
    FOREIGN KEY (`alumno`)
    REFERENCES `mydb`.`alumno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estaen_centro`
    FOREIGN KEY (`centro`)
    REFERENCES `mydb`.`centro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sede` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `region` ENUM('España', 'Honduras') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apadrinable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`apadrinable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`apadrinable` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_apadrinable_alumno`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`alumno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apadrinamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`apadrinamiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`apadrinamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apadrinado` INT NOT NULL,
  `padrino` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_apadrinamiento_apadrinable_idx` (`apadrinado` ASC),
  INDEX `fk_apadrinamiento_socio_idx` (`padrino` ASC),
  CONSTRAINT `fk_apadrinamiento_apadrinable`
    FOREIGN KEY (`apadrinado`)
    REFERENCES `mydb`.`apadrinable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apadrinamiento_socio`
    FOREIGN KEY (`padrino`)
    REFERENCES `mydb`.`socio` (`numero_de_socio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordinador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`coordinador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`coordinador` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_coordinador_usuariolocal`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`usuario_local` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_sede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_sede` (
  `id` INT NOT NULL,
  `sede` INT NOT NULL,
  INDEX `fk_usuariosede_sede_idx` (`sede` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuariosede_sede`
    FOREIGN KEY (`sede`)
    REFERENCES `mydb`.`sede` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UsuarioSede_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agentes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agentes` (
  `id` INT NOT NULL,
  INDEX `fk_usuariosede_agente_idx` (`id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuariosede_agente`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`usuario_sede` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administracion_apadrinamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`administracion_apadrinamiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`administracion_apadrinamiento` (
  `apadrinamiento` INT NOT NULL,
  `agente` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  INDEX `fk_adminap_agente_idx` (`agente` ASC),
  PRIMARY KEY (`apadrinamiento`, `agente`),
  CONSTRAINT `fk_adminap_apadrinamiento`
    FOREIGN KEY (`apadrinamiento`)
    REFERENCES `mydb`.`apadrinamiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adminap_agente`
    FOREIGN KEY (`agente`)
    REFERENCES `mydb`.`agentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`gerente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`gerente` (
  `id` INT NOT NULL,
  INDEX `fk_usuariosede_gerente_idx` (`id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gerente_responsable`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`responsable_economico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuariosede_gerente`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`usuario_sede` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`envio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`envio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`envio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `apadrinamiento` INT NOT NULL,
  `estado` ENUM('Preparado', 'Enviado', 'Recibido') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `apadrinamiento_UNIQUE` (`apadrinamiento` ASC),
  CONSTRAINT `fk_envio_apadrinamiento`
    FOREIGN KEY (`apadrinamiento`)
    REFERENCES `mydb`.`apadrinamiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`becado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`becado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`becado` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_becado_alumno`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`alumno` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
